server:
  port: 8100
spring:
  application:
    name: learn-mybatis

  datasource:
    one:
      url: jdbc:mysql://localhost:3306/springboot_learn_persistent_mybatis_one?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456789
    two:
      url: jdbc:mysql://localhost:3306/springboot_learn_persistent_mybatis_two?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456789


appli: 123

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*Mapper.xml
