server:
  port: 8090

spring:
  application:
    name: learn-rabbitmq
  rabbitmq:
    addresses: localhost
    port: 5672
    username: futao
    password: 123456789
    virtual-host: /springboot-learn
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        # 每个队列启动的消费者数量
        concurrency: 5
        # 每个队列最大的消费者数量
        max-concurrency: 5
        # 手动签收ACK-那么需要在代码中手动设置ACK
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5



debug: true