server:
  port: 8090

spring:
  application:
    name: learn-rabbitmq
  rabbitmq:
    addresses: localhost
    port: 5672
    username: futao
    password: 123456789
    virtual-host: /springboot-learn
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: false
    template:
      mandatory: true
    listener:
      simple:
        # 每个队列启动的消费者数量
        concurrency: 5
        # 每个队列最大的消费者数量
        max-concurrency: 5
        # 手动签收ACK-那么需要在代码中手动设置ACK
        acknowledge-mode: manual
        retry:
          enabled: true
          # 最大重试次数
          max-attempts: 5
        # 每次从RabbitMQ获取的消息数量
        prefetch: 5

  datasource:
    url: jdbc:mysql://localhost:3306/springboot_learn_rabbitmq?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456789

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
debug: true