server:
  port: 8120

spring:
  application:
    name: learn-redis
  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:      #使用的是jedis（或者lettuce）
      pool:
        max-active: 8     #最大连接数
        max-idle: 8       #最大空闲连接数
        min-idle: 0       #最小空闲连接数
        max-wait: -1ms    #最大阻塞时间（-1没有限制）
