server:
  port: 8110

spring:
  application:
    name: learn-jpa
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
  datasource:
    one:
      url: jdbc:mysql://localhost:3306/springboot_learn_persistent_jpa?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456789
    two:
      url: jdbc:mysql://localhost:3306/springboot_learn_persistent_jpa_two?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456789