server:
  port: 8110

spring:
  application:
    name: learn-jpa
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    database-platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_learn_persistent_jpa?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456789